// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
//		如存在本生成代码外的新需求，请在相同命名空间下创建同名分部类实现 UserData6ConfigurationAppend 分部方法。
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using FluentJson.Configuration;
using FluentJson;
using XIMALAYA.PCDesktop.Core.Data.Decorator;
using XIMALAYA.PCDesktop.Core.Models.User;

namespace XIMALAYA.PCDesktop.Core.Data
{
    /// <summary>
    ///     UserData6
    /// </summary>
    /// <typeparam name="T"></typeparam>
    public partial class UserData6Decorator<T> : Decorator<T>
    {
        partial void doAddOtherConfig();
        /// <summary>
        ///     
        /// </summary>
        /// <typeparam name="result"></typeparam>
        public UserData6Decorator(Result<T> result)
            : base(result)
        {

        }
        /// <summary>
        ///     
        /// </summary>
        /// <typeparam name="result"></typeparam>
        public override void doAddConfig()
        {
            base.doAddConfig();
            this.Config.MapType<UserData>(map => map
                                    .Field<System.String>(field => field.NickName, type => type.To("nickname"))
                    .Field<System.String>(field => field.BackGroundLogo, type => type.To("backgroundPic"))
                    .Field<System.Int32>(field => field.BirthDay, type => type.To("birthDay"))
                    .Field<System.Int32>(field => field.BirthMonth, type => type.To("birthMonth"))
                    .Field<System.Int32>(field => field.BirthYear, type => type.To("birthYear"))
                    .Field<System.String>(field => field.City, type => type.To("city"))
                    .Field<System.String>(field => field.Country, type => type.To("country"))
                    .Field<System.Int64>(field => field.CreateDate, type => type.To("createTime"))
                    .Field<System.String>(field => field.Email, type => type.To("email"))
                    .Field<System.String>(field => field.Gender, type => type.To("gender"))
                    .Field<System.Boolean>(field => field.IsVerified, type => type.To("isVerified"))
                    .Field<System.String>(field => field.MobileLargeLogo, type => type.To("largePic"))
                    .Field<System.Int64>(field => field.LastUpdateDate, type => type.To("lastModifyTime"))
                    .Field<System.String>(field => field.MobileSmallLogo, type => type.To("smallPic"))
                    .Field<System.String>(field => field.MobileMiddleLogo, type => type.To("middlePic"))
                    .Field<System.String>(field => field.PersonDescribe, type => type.To("personDescribe"))
                    .Field<System.String>(field => field.PersonalSignature, type => type.To("personalSignature"))
                    .Field<System.String>(field => field.Province, type => type.To("province"))
                    .Field<System.String>(field => field.PTitle, type => type.To("ptitle"))
                    .Field<System.Int64>(field => field.Uid, type => type.To("uid"))
            );
            this.doAddOtherConfig();
        }
    }
}
