// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
//		如存在本生成代码外的新需求，请在相同命名空间下创建同名分部类实现 SoundData6ConfigurationAppend 分部方法。
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using FluentJson.Configuration;
using FluentJson;
using XIMALAYA.PCDesktop.Core.Data.Decorator;
using XIMALAYA.PCDesktop.Core.Models.Sound;

namespace XIMALAYA.PCDesktop.Core.Data
{
    /// <summary>
    ///     SoundData6
    /// </summary>
    /// <typeparam name="T"></typeparam>
    public partial class SoundData6Decorator<T> : Decorator<T>
    {
        partial void doAddOtherConfig();
        /// <summary>
        ///     
        /// </summary>
        /// <typeparam name="result"></typeparam>
        public SoundData6Decorator(Result<T> result)
            : base(result)
        {

        }
        /// <summary>
        ///     
        /// </summary>
        /// <typeparam name="result"></typeparam>
        public override void doAddConfig()
        {
            base.doAddConfig();
            this.Config.MapType<SoundData>(map => map
                                    .Field<System.Int64>(field => field.TrackId, type => type.To("id"))
                    .Field<System.Int64>(field => field.AlbumID, type => type.To("album_id"))
                    .Field<System.String>(field => field.AlbumTitle, type => type.To("album_title"))
                    .Field<System.Int64>(field => field.CategoryID, type => type.To("category_id"))
                    .Field<System.Int64>(field => field.CommentCount, type => type.To("comments_counts"))
                    .Field<System.String>(field => field.CoverLarge, type => type.To("coverLarge"))
                    .Field<System.String>(field => field.CoverSmall, type => type.To("coverSmall"))
                    .Field<System.Int64>(field => field.CreateAt, type => type.To("createdAt"))
                    .Field<System.Double>(field => field.Duration, type => type.To("duration"))
                    .Field<System.Int64>(field => field.LikeCount, type => type.To("favorites_counts"))
                    .Field<System.String>(field => field.Intro, type => type.To("intro"))
                    .Field<System.Boolean>(field => field.IsRelay, type => type.To("isRelay"))
                    .Field<System.Boolean>(field => field.IsVerified, type => type.To("isVerified"))
                    .Field<System.String>(field => field.NickName, type => type.To("nickname"))
                    .Field<System.String>(field => field.PlayUrl32, type => type.To("play_path_32"))
                    .Field<System.String>(field => field.PlayUrl64, type => type.To("play_path_64"))
                    .Field<System.Int64>(field => field.PlayCount, type => type.To("plays_counts"))
                    .Field<System.Int64>(field => field.ShareCount, type => type.To("shares_counts"))
                    .Field<System.String>(field => field.SmallLogo, type => type.To("smallLogo"))
                    .Field<System.String>(field => field.Title, type => type.To("title"))
                    .Field<System.Int64>(field => field.UID, type => type.To("uid"))
                    .Field<System.Int32>(field => field.UserSource, type => type.To("user_source"))
            );
            this.doAddOtherConfig();
        }
    }
}
