// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
//		如存在本生成代码外的新需求，请在相同命名空间下创建同名分部类实现 AlbumData5ConfigurationAppend 分部方法。
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using FluentJson.Configuration;
using FluentJson;
using XIMALAYA.PCDesktop.Core.Data.Decorator;
using XIMALAYA.PCDesktop.Core.Models.Album;

namespace XIMALAYA.PCDesktop.Core.Data
{
    /// <summary>
    ///     AlbumData5
    /// </summary>
    /// <typeparam name="T"></typeparam>
    public partial class AlbumData5Decorator<T> : Decorator<T>
    {
        partial void doAddOtherConfig();
        /// <summary>
        ///     
        /// </summary>
        /// <typeparam name="result"></typeparam>
        public AlbumData5Decorator(Result<T> result)
            : base(result)
        {

        }
        /// <summary>
        ///     
        /// </summary>
        /// <typeparam name="result"></typeparam>
        public override void doAddConfig()
        {
            base.doAddConfig();
            this.Config.MapType<AlbumData>(map => map
                                    .Field<System.Int64>(field => field.AlbumID, type => type.To("album_id"))
                    .Field<System.String>(field => field.AlbumCoverUrl86, type => type.To("album_cover_path_86"))
                    .Field<System.String>(field => field.AlbumCoverUrl290, type => type.To("album_cover_path_290"))
                    .Field<System.String>(field => field.AlbumCoverUrl640, type => type.To("album_cover_path_640"))
                    .Field<System.Int64>(field => field.Uid, type => type.To("album_uid"))
                    .Field<System.String>(field => field.Intro, type => type.To("intro"))
                    .Field<System.Int64>(field => field.PlayCount, type => type.To("plays_counts"))
                    .Field<System.String>(field => field.Title, type => type.To("title"))
                    .Field<System.Int64>(field => field.LastUptrackDate, type => type.To("last_uptrack_at"))
            );
            this.doAddOtherConfig();
        }
    }
}
